# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb3fae77607f7b8e43c23f9fad309353a9e6dad06b89a45d2d80ea3c5a28ffc8493d01c9967fec19dccd6ee177d865b69bf853ca8a3fbdce29a6ec2e5971fa4

test:
  secret_key_base: 5d1a4cc56b7924e66e51d8894993157cd2cbe072aa2b17f9f849e586800ede6f541d47d713486cd872ee7fc7b8a9fb75cd7b308f27bf69dd9d3da08fd722fd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
